export default {
	AUTH: "AUTH",
	AUTH_RESET: "AUTH_RESET",
	GLOBAL: "GLOBAL",
	GLOBAL_RESET: "GLOBAL_RESET",
	BUSINESS: "BUSINESS",
	BUSINESS_RESET: "BUSINESS_RESET",
	INVOICE: "INVOICE",
	INVOICE_RESET: "INVOICE_RESET"
}